INSERT INTO institua(name)
	VALUES ('TRIẾT HỌC'),
    ('KINH TẾ CHÍNH TRỊ HỌC'),
    ('KINH TẾ'),
    ('CHỦ NGHĨA XÃ HỘI KHOA HỌC'),
    ('HỒ CHÍ MINH VÀ CÁC LÃNH TỤ CỦA ĐẢNG'),
    ('LỊCH SỬ ĐẢNG'),
    ('XÂY DỰNG ĐẢNG'),
    ('TÔN GIÁO VÀ TÍN NGƯỠNG'),
    ('VIỆN CHÍNH TRỊ HỌC'),
    ('NHÀ NƯỚC VÀ PHÁP LUẬT'),
    ('VĂN HÓA VÀ PHÁT TRIỂN'),
    ('QUAN HỆ QUỐC TẾ'),
    ('QUYỀN CON NGƯỜI'),
    ('XÃ HỘI HỌC VÀ PHÁT TRIỂN'),
    ('LÃNH ĐẠO HỌC VÀ CHÍNH SÁCH CÔNG'),
    ('THÔNG TIN KHOA HỌC'),
    ('TẠP CHÍ LÝ LUẬN CHÍNH TRỊ'),
    ('NHÀ XUẤT BẢN LÝ LUẬN CHÍNH TRỊ')
    